application: backplanejs
version: 1
runtime: python
api_version: 1

handlers:
- url: /backplanejs-0.6.1
  static_dir: backplanejs-0.6.1

- url: /backplanejs-0.6.0
  static_dir: backplanejs-0.6.0

- url: /backplanejs-0.5.0
  static_dir: backplanejs-0.5.0

- url: /backplanejs-0.4.0
  static_dir: backplanejs-0.4.0

- url: /samples
  static_dir: samples

- url: /unit-tests
  static_dir: ../../_unit-tests

- url: /work
  static_dir: ../../work

- url: /rdfa-viewer.html
  static_files: rdfa-viewer.html
  upload: rdfa-viewer.html

- url: /.*
  script: rdfa.py
