application: backplanejs
version: 1
runtime: python
api_version: 1

handlers:
- url: /backplanejs-(.*)/(.*)
  static_files: backplanejs-\1/\2
  upload: backplanejs-(.*)/(.*)
  expiration: 1825d

- url: /samples
  static_dir: samples

- url: /unit-tests
  static_dir: unit-tests

- url: /work
  static_dir: ../work

- url: /rdfa-viewer.html
  static_files: rdfa-viewer.html
  upload: rdfa-viewer.html

- url: /.*
  script: rdfa.py

skip_files: |
  ^work/(.*)$|
  ^(.*/)?(
    (app\.yaml)|
    (app\.yml)|
    (index\.yaml)|
    (index\.yml)|
    (#.*#)|
    (.*~)|
    (.*\.py[co])|
    (.*/RCS/.*)|
    (\..*)|
  )$
